"""test

Revision ID: 4b2228b9bacc
Revises: 
Create Date: 2020-12-06 12:18:24.533632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from tenent.multy_tenent import pre_schema


# revision identifiers, used by Alembic.
revision = '4b2228b9bacc'
down_revision = None
branch_labels = None
depends_on = None


@pre_schema(exclude=["public"])
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenent_users',
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


@pre_schema(exclude=["public"])
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tenent_users')
    # ### end Alembic commands ###
